upstream v1  {
    server mc:7000;
}

server {
    listen 8080;

    location / {
        proxy_pass http://frontend:8000;
        proxy_set_header Host $Host;
        proxy_set_header Connection "";  
    }

    location /v1 {
        proxy_pass http://v1;
        proxy_set_header Host $Host;
        proxy_set_header Connection "";  
    }
}